# Generated by Django 3.0.3 on 2020-02-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='título')),
                ('texto', models.TextField(max_length=1000, verbose_name='texto')),
            ],
        ),
    ]
